# Generated by Django 6.0.3 on 2026-03-08 08:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.IntegerField(help_text='Positive for credit, negative for debit')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchased with Money'), ('message', 'Spent on Message'), ('reward', 'Earned as Reward'), ('bonus', 'Bonus Coins'), ('refund', 'Refund'), ('admin', 'Admin Adjustment')], db_index=True, max_length=20)),
                ('balance_after', models.PositiveIntegerField(help_text='Balance after this transaction')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'coin_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
