# Generated by Django 5.2.7 on 2025-11-19 06:10

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_devicetoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinWallet',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='coin_wallet', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance', models.PositiveIntegerField(default=10, help_text='Current coin balance')),
                ('total_earned', models.PositiveIntegerField(default=10, help_text='Total coins earned (including initial)')),
                ('total_spent', models.PositiveIntegerField(default=0, help_text='Total coins spent')),
                ('total_purchased', models.PositiveIntegerField(default=0, help_text='Total coins purchased with real money')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'coin_wallets',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('participant_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_participant_1', to=settings.AUTH_USER_MODEL)),
                ('participant_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_participant_2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conversations',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyMessageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=datetime.date.today)),
                ('total_messages_sent', models.PositiveIntegerField(default=0)),
                ('free_messages_used', models.PositiveIntegerField(default=0)),
                ('paid_messages_sent', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_quotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_message_quotas',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('content', models.TextField(help_text='Message content (max 1000 characters)', max_length=1000)),
                ('coin_cost', models.PositiveIntegerField(default=0, help_text='Number of coins spent to send this message')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.IntegerField(help_text='Positive for credit, negative for debit')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchased with Money'), ('message', 'Spent on Message'), ('reward', 'Earned as Reward'), ('bonus', 'Bonus Coins'), ('refund', 'Refund'), ('admin', 'Admin Adjustment')], db_index=True, max_length=20)),
                ('balance_after', models.PositiveIntegerField(help_text='Balance after this transaction')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='messaging.coinwallet')),
                ('related_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin_transactions', to='messaging.message')),
            ],
            options={
                'db_table': 'coin_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['participant_1', '-last_message_at'], name='conversatio_partici_018d50_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['participant_2', '-last_message_at'], name='conversatio_partici_f6ae6f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('participant_1', 'participant_2')},
        ),
        migrations.AddIndex(
            model_name='dailymessagequota',
            index=models.Index(fields=['user', 'date'], name='daily_messa_user_id_b0317f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailymessagequota',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='messages_convers_3ebb41_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', '-created_at'], name='messages_sender__7375e3_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver', 'is_read'], name='messages_receive_c45f39_idx'),
        ),
        migrations.AddIndex(
            model_name='cointransaction',
            index=models.Index(fields=['wallet', '-created_at'], name='coin_transa_wallet__894c8d_idx'),
        ),
        migrations.AddIndex(
            model_name='cointransaction',
            index=models.Index(fields=['transaction_type', '-created_at'], name='coin_transa_transac_914cd9_idx'),
        ),
    ]
