# Generated by Django 5.2.7 on 2025-11-07 04:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_is_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='matches_preferences', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('show_only_verified', models.BooleanField(default=False, help_text='Show only verified users')),
                ('hide_seen_profiles', models.PositiveIntegerField(default=True, help_text='Hide profile already viewed')),
                ('age_importance', models.PositiveIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Deal breaker')], default=2)),
                ('distance_importance', models.PositiveIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Deal breaker')], default=3)),
                ('interests_importance', models.PositiveIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Deal breaker')], default=4, help_text='Weight for shared interests in matching')),
                ('relationship_goal_importance', models.PositiveIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Deal breaker')], default=5)),
                ('min_profile_completion', models.PositiveIntegerField(default=50, help_text='Minimum profile completion percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_preferences',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, choices=[('inappropriate', 'Inappropriate Behavior'), ('harassment', 'Harassment'), ('spam', 'Spam'), ('fake', 'Fake Profile'), ('other', 'Other')], default='other', max_length=20)),
                ('note', models.TextField(blank=True, help_text='Optional note for the block')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blocks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['blocker', '-created_at'], name='blocks_blocker_7836e1_idx'), models.Index(fields=['blocked_user', '-created_at'], name='blocks_blocked_e4b07d_idx')],
                'unique_together': {('blocker', 'blocked_user')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('passed', 'Passed'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('match_score', models.PositiveIntegerField(db_index=True, help_text='Compatibility score from 0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_mutual', models.BooleanField(db_index=True, default=False, help_text='True if both users liked each other')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_at', models.DateTimeField(blank=True, help_text='When mutual match was made', null=True)),
                ('matched_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_initiated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matches',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='matches_user_id_471a1c_idx'), models.Index(fields=['user', 'is_mutual'], name='matches_user_id_6331ce_idx'), models.Index(fields=['matched_user', 'status'], name='matches_matched_b8b2b1_idx'), models.Index(fields=['-match_score', 'status'], name='matches_match_s_3b4a63_idx'), models.Index(fields=['user', '-created_at'], name='matches_user_id_cca2f3_idx')],
                'unique_together': {('user', 'matched_user')},
            },
        ),
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_duration_seconds', models.PositiveIntegerField(default=0, help_text='Duration of the view in seconds')),
                ('resulted_in_swipe', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('viewed_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views_received', to=settings.AUTH_USER_MODEL)),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile_views',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['viewer', '-created_at'], name='profile_vie_viewer__6f7575_idx'), models.Index(fields=['viewed_profile', '-created_at'], name='profile_vie_viewed__45cc20_idx')],
            },
        ),
        migrations.CreateModel(
            name='SwipeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(choices=[('like', 'Like'), ('pass', 'Pass')], db_index=True, max_length=20)),
                ('match_score_at_swipe', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_swipes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipe_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'swipe_actions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='swipe_actio_user_id_2dd009_idx'), models.Index(fields=['user', 'action'], name='swipe_actio_user_id_264053_idx'), models.Index(fields=['target_user', 'action'], name='swipe_actio_target__ee9759_idx')],
                'unique_together': {('user', 'target_user')},
            },
        ),
    ]
