# Generated by Django 6.0.3 on 2026-03-08 08:05

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, choices=[('inappropriate', 'Inappropriate Behavior'), ('harassment', 'Harassment'), ('spam', 'Spam'), ('fake', 'Fake Profile'), ('other', 'Other')], default='other', max_length=20)),
                ('note', models.TextField(blank=True, help_text='Optional note for the block')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blocks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('rejected', 'Rejected'), ('passed', 'Passed'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('match_score', models.PositiveIntegerField(db_index=True, help_text='Compatibility score from 0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_mutual', models.BooleanField(db_index=True, default=False, help_text='True if both users liked each other')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_at', models.DateTimeField(blank=True, help_text='When mutual match was made', null=True)),
            ],
            options={
                'db_table': 'matches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_duration_seconds', models.PositiveIntegerField(default=0, help_text='Duration of the view in seconds')),
                ('resulted_in_swipe', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'profile_views',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SwipeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(choices=[('like', 'Like'), ('pass', 'Pass')], db_index=True, max_length=20)),
                ('match_score_at_swipe', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'swipe_actions',
                'ordering': ['-created_at'],
            },
        ),
    ]
