# Generated by Django 6.0.3 on 2026-03-08 08:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='matches_preferences', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('show_only_verified', models.BooleanField(default=False, help_text='Show only verified users')),
                ('hide_seen_profiles', models.BooleanField(default=True, help_text='Hide profiles already viewed')),
                ('age_importance', models.PositiveIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Deal breaker')], default=2)),
                ('distance_importance', models.PositiveIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Deal breaker')], default=3)),
                ('interests_importance', models.PositiveIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Deal breaker')], default=4, help_text='Weight for shared interests in matching')),
                ('relationship_goal_importance', models.PositiveIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Deal breaker')], default=4)),
                ('min_profile_completion', models.PositiveIntegerField(default=50, help_text='Minimum profile completion percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_preferences',
            },
        ),
        migrations.AddField(
            model_name='block',
            name='blocked_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='block',
            name='blocker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='matched_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_initiated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profileview',
            name='viewed_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profileview',
            name='viewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='swipeaction',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_swipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='swipeaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipe_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['blocker', '-created_at'], name='blocks_blocker_7836e1_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['blocked_user', '-created_at'], name='blocks_blocked_e4b07d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('blocker', 'blocked_user')},
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['user', 'status'], name='matches_user_id_471a1c_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['user', 'is_mutual'], name='matches_user_id_6331ce_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['matched_user', 'status'], name='matches_matched_b8b2b1_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['-match_score', 'status'], name='matches_match_s_3b4a63_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['user', '-created_at'], name='matches_user_id_cca2f3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('user', 'matched_user')},
        ),
        migrations.AddIndex(
            model_name='profileview',
            index=models.Index(fields=['viewer', '-created_at'], name='profile_vie_viewer__6f7575_idx'),
        ),
        migrations.AddIndex(
            model_name='profileview',
            index=models.Index(fields=['viewed_profile', '-created_at'], name='profile_vie_viewed__45cc20_idx'),
        ),
        migrations.AddIndex(
            model_name='swipeaction',
            index=models.Index(fields=['user', '-created_at'], name='swipe_actio_user_id_2dd009_idx'),
        ),
        migrations.AddIndex(
            model_name='swipeaction',
            index=models.Index(fields=['user', 'action'], name='swipe_actio_user_id_264053_idx'),
        ),
        migrations.AddIndex(
            model_name='swipeaction',
            index=models.Index(fields=['target_user', 'action'], name='swipe_actio_target__ee9759_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='swipeaction',
            unique_together={('user', 'target_user')},
        ),
    ]
